spring.application.name=backend

# MySQL / TiDB Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/field_service_management?useSSL=true}
spring.datasource.username=${DB_USERNAME:2aBvKriS9i6jw45.root}
spring.datasource.password=${DB_PASSWORD:njJTZJ1cVyzNHInk}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}